config/routes.rb
Rails.application.routes.draw do
  root 'disks#index'

  resources :disks do
    collection {post :import}
  end

  resources :groups, only: [:index, :show]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      match 'reports/report' => 'reports#report', :via => :post
    end
  end
end

app/models/disk.rb
class Disk < ApplicationRecord
  DTAP = ['development', 'test', 'acceptance', 'production']

  belongs_to :content
  belongs_to :department
  belongs_to :owner
  belongs_to :software
  belongs_to :group
  has_and_belongs_to_many :systems, dependent: :destroy
  # Test it
  has_paper_trail on: [:update], only: [:volume, :utilization]
  default_scope {order(unit: :asc)}

  after_create :calculate_group_stats
  after_update :calculate_group_stats, if: :changed_disk_stats?
  # duplicated CALLBACKS overrides themselves
  # after_update :calculate_group_stats, if: :saved_change_to_capacity?
  # after_update :calculate_group_stats, if: :saved_change_to_group_id?
  # after_update :calculate_old_group_stats, if: :saved_change_to_group_id?

  #################
  # Default methods
  #################

  def empty?
    self.volume[0..1] == 'TM'
  end

  def unit_to_hex
    self.unit.to_s(16)
  end

  def to_chart_array
    [self.updated_at, self.utilization]
  end

  def custom_capacity(units)
    case units
      when "MB"
        self.capacity / 1024
      when "GB"
        self.capacity / 1048576
      else
        self.capacity
    end
  end

  def changed_disk_stats?
    saved_change_to_utilization? || saved_change_to_capacity? || saved_change_to_group_id?
  end

  def calculate_group_stats
    calculate_old_group_stats if saved_change_to_group_id?
    if self.group && self.group.name != 'NOGROUP'
      self.group.capacity = self.group.disks.map {|d| d.capacity}.sum
      if self.group.capacity != 0
        used_kb = self.group.disks.map {|d| d.capacity * d.utilization / 100}.sum
        self.group.utilization = (used_kb * 100) / self.group.capacity
      else
        self.group.utilization = 0
      end
      self.group.save!
    end
  end

  # make tests!
  def calculate_old_group_stats
    if self.group_id_was
      old_group = Group.find(self.group_id_was)
      if old_group.name != 'NOGROUP'
        old_group.capacity = old_group.disks.map {|d| d.capacity}.sum
        if old_group.capacity != 0
          used_kb = old_group.disks.map {|d| d.capacity * d.utilization / 100}.sum
          old_group.utilization = (used_kb * 100) / old_group.capacity
        else
          old_group.utilization = 0
        end
        old_group.save!
      end
    end
  end

  def report(sysname, disk)
    # Creates new disk if no exists
    # Add disk systems relation if no exists
    #
    #
    # CREATE RELATED RESOURCES CHECK

    self.unit = disk[:unit].hex if self.new_record?
    self.attributes = {
        volume: disk[:volume],
        capacity: disk[:capacity],
        utilization: disk[:utilization]
    }

    # OWNER
    self.owner = Owner.where(name: 'NOOWNER').first || Owner.create!(name: 'NOOWNER') unless self.owner

    # SOFTWARE
    self.software = Software.where(name: 'NOSOFTWARE').first || Software.create!(name: 'NOSOFTWARE') unless self.software

    # CONTENT
    self.content = Content.where(name: 'NOCONTENT').first || Content.create!(name: 'NOCONTENT') unless self.content

    # DEPARTMENT
    self.department = Department.where(name: 'NODEPARTMENT').first || Department.create!(name: 'NODEPARTMENT') unless self.department

    # STORGROUP
    self.group = Group.where(name: 'NOGROUP').first || Group.create!(name: 'NOGROUP')
    unless disk[:storgroup] == ''
      self.group = Group.where(name: disk[:storgroup]).first || Group.create!(name: disk[:storgroup])
    end

    # SYSTEM
    if self.systems.all.map(&:name).exclude? sysname
      system = System.where(name: sysname).first || System.create!(name: sysname)
      self.systems << system
    end
  end

  def self.import2(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      disk = find_by_id(row["id"]) || new
      disk.attributes = row.to_hash.slice(*row.to_hash.keys)
      disk.save!
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      disk = find_by_id(row["id"]) || new
      # disk.attributes = row.to_hash.slice(*row.to_hash.keys )
      department = Department.where(name: row["department"]).first || Department.create!(name: row["department"])
      content = Content.where(name: row["content"]).first || Content.create!(name: row["content"])
      software = Software.where(name: row["software"]).first || Software.create!(name: row["software"])
      owner = Owner.where(name: row["owner"]).first || Owner.create!(name: row["owner"])
      disk.attributes = {
          id: row["id"],
          unit: row["unit"],
          volume: row["volume"],
          capacity: row["capacity"],
          utilization: row["utilization"],
          pprc_secondary: row["pprc secondary"],
          dtap: row["dtap"],
          added_at: row["added_at"],
          department: department,
          content: content,
          software: software,
          owner: owner
      }
      if row["system"] && disk.systems.all.map(&:name) != row["system"].split
        row["system"].split.each do |sysname|
          system = System.where(name: sysname).first || System.create!(name: sysname)
          disk.systems << system
        end
      end
      disk.save
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then
        Roo::Csv.new(file.path, nil, :ignore)
      when ".xls" then
        Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then
        Roo::Excelx.new(file.path)
      else
        raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/api/v1/disks_controller.rb
class Api::V1::DisksController < ApplicationController
  #!!!! create with doorkeeper
  skip_before_action :verify_authenticity_token
  respond_to :json

  def show
    respond_with(Disk.find(params[:id]))
  end

  def report
    params.delete :disk
    # disks = params[:report].to_h
    head :ok
  end

  private

  def question_params
    params.require(:report).permit(:date_time, :system, disks: [:unit, :volume, :capacity, :utilization, :storgroup])
  end
end

app/controllers/disks_controller.rb
class DisksController < ApplicationController
  before_action :take_disk, only: [:show, :destroy, :update]

  respond_to :xls, :xlsx

  def index
    # respond_with(@disks = Disk.all)

    if request.format == :html
      respond_with(@disks = Disk.paginate(:page => params[:page], :per_page => 30))
    else
      respond_with(@disks=Disk.all)
    end

    # respond_to do |format|
    #   format.html { render :html => @disks = Disk.paginate(:page => params[:page], :per_page => 30) }# show.html.erb
    #   format.xls  { render :xls => @disks = Disk.all }
    # end

  end

  def new
    respond_with(@disk = Disk.new)
  end

  def create
    @disk = Disk.create(disk_params)
    respond_with(@disk)
  end

  def update
    @disk.update(disk_params)
    respond_with(@disk)
  end

  def destroy
    respond_with(@disk.destroy)
  end

  def show
    respond_with(@disk)
  end

  def import
    Disk.import(params[:file])
    redirect_to root_url, notice: 'Disks imported'
  end

  private
  def disk_params
    params.require(:disk).permit(:unit, :volume, :group_id, :capacity, :utilization,
                                 :pprc_secondary, :dtap, :added_at, :department_id,
                                 :content_id, :software_id, :owner_id, { system_ids:[]})
  end

  def take_disk
    @disk = Disk.find(params[:id])
  end
end

app/helpers/disks_helper.rb
module DisksHelper
  def utilization_color(disk)
    case disk.utilization
      when 0..70
        "#FFFFFF"
      when 71..90
        "#F0FF00"
      when 91..100
        "#FF0000"
    end
  end

  def capacity_color(disk)
    case disk.capacity
      when 0..4000000
        "#FFFFFF"
      when 4000001..10000000
        "#FF99CC"
      when 10000001..28000000
        "#FFCC99"
      when 28000001..Float::INFINITY
        "#FFCC00"
    end
  end
end

app/views/disks/_disk.html.slim
tr bgcolor=capacity_color(disk)
  td
    = link_to disk.unit_to_hex.upcase, disk_path(disk.id)
  td = disk.volume
  td = link_to disk.group.name, group_path(disk.group) if disk.group
  td
    = disk.custom_capacity('GB')
    |  GB
  td bgcolor=utilization_color(disk)
    = disk.utilization
  td = disk.pprc_secondary
  td = disk.dtap
  td = disk.added_at
  td = disk.department.name if disk.department
  td = disk.content.name if disk.content
  td = disk.software.name if disk.software
  td
    - disk.systems.each do |system|
      li
        = system.name
  td = disk.owner.name

app/views/disks/_edit_disk.html.slim
= form_with model: @disk do |f|
  div class='col-xs-4'
    = f.label :unit
    = f.text_field :unit, id: 'disk_unit', class: 'form-control'
    br
    = f.label :volume
    = f.text_field :volume, id: 'disk_volume', class: 'form-control'
    br
    = f.label :group_id
    = f.select :group_id, Group.all.collect {|d| [d.name, d.id]}, {}, {class: 'form-control'}
    br
    = f.label :capacity
    = f.text_field :capacity, id: 'disk_capacity', class: 'form-control'
    br
    = f.label :utilization
    = f.text_field :utilization, id: 'disk_utilization', class: 'form-control'
    br
    = f.label :pprc_secondary
    = f.text_field :pprc_secondary, id: 'disk_pprc_secondary', class: 'form-control'
    br
    = f.label :dtap
    = f.select :dtap, Disk::DTAP, {}, {class:'form-control'}
    br
    = f.label :added_at
    = f.date_field :added_at, placeholder: 'date', class: 'form-control', :value => Time.now.strftime('%Y-%d-%m')
    br
    = f.label :department_id
    = f.select :department_id, Department.all.collect {|d| [ d.name, d.id ] }, {}, {class:'form-control'}
    br
    = f.label :content_id
    = f.select :content_id, Content.all.collect {|d| [ d.name, d.id ] }, {}, {class:'form-control'}
    br
    = f.label :owner_id
    = f.select :owner_id, Owner.all.collect {|d| [d.name, d.id]}, {}, {class:'form-control'}
    br
    = f.label :software_id
    = f.select :software_id, Software.all.collect {|d| [d.name, d.id]}, {}, {class:'form-control'}
    br
    = f.label :system_id

    div class="[ form-group ]"
      = f.collection_check_boxes :system_ids, System.all, :id, :name, :include_hidden => false do |s|
        br
        = s.check_box id: "disk_system_ids_#{s.value}", autocomplete: "off"
        div class="[ btn-group ]"
          label for="disk_system_ids_#{s.value}" class="[ btn btn-default ]"
            span class="[ glyphicon glyphicon-plus ]"
            span class="[ glyphicon glyphicon-minus ]"
          = s.label for: "disk_system_ids_#{s.value}", class: "[ btn btn-default active ]"

    br
    = f.submit class:'btn btn-success'

app/views/disks/index.html.slim
h1 align = 'center' Disks list
div class='container-fluid'
  button class="btn btn-info" type="button" data-toggle="collapse" data-target="#collapseDownload" aria-expanded="false" aria-controls="collapseDownload"
    |Download | Import
  div class="collapse" id="collapseDownload"
    div class="well"
      label Download:
      br
      = link_to 'Excel .xls',disks_path(format: 'xls')
      br
      = link_to 'Excel .xlsx',disks_path(format: 'xlsx')
      br
      label Import:
      br
      = form_tag import_disks_path, multipart: true do
        = file_field_tag :file
        = submit_tag "Import"
  p

    table class="table table-bordered"
      tr
        th unit
        th volume
        th sms group
        th capacity
        th utilization
        th pprc secondary
        th dev/test/acc/prod
        th added at
        th department
        th content
        th software
        th system
        th owner
        = render @disks
        = will_paginate @disks

app/views/disks/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Styles>
    <Style ss:ID="s3">
      <Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/>
      <Borders>
       <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
      </Borders>
    </Style>
    <Style ss:ID="s9">
      <Interior ss:Color="#FF99CC" ss:Pattern="Solid"/>
      <Borders>
       <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
      </Borders>
    </Style>
    <Style ss:ID="s27">
      <Interior ss:Color="#FFCC99" ss:Pattern="Solid"/>
      <Borders>
       <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
      </Borders>
    </Style>
    <Style ss:ID="s54">
      <Interior ss:Color="#FFCC00" ss:Pattern="Solid"/>
      <Borders>
       <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
      </Borders>
    </Style>
    <Style ss:ID="free">
      <Interior ss:Color="#66FF66" ss:Pattern="Solid"/>
      <Borders>
       <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
      </Borders>
    </Style>
    <Style ss:ID="utilMed">
      <Interior ss:Color="#F0FF00" ss:Pattern="Solid"/>
      <Borders>
       <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
      </Borders>
    </Style>
    <Style ss:ID="utilHigh">
      <Interior ss:Color="#FF0000" ss:Pattern="Solid"/>
      <Borders>
       <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
       <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
      </Borders>
    </Style>
  </Styles>
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">unit</Data></Cell>
        <Cell><Data ss:Type="String">volume</Data></Cell>
        <Cell><Data ss:Type="String">sms group</Data></Cell>
        <Cell><Data ss:Type="String">capacity</Data></Cell>
        <Cell><Data ss:Type="String">utilization</Data></Cell>
        <Cell><Data ss:Type="String">pprc secondary</Data></Cell>
        <Cell><Data ss:Type="String">dev/test/acc/prod</Data></Cell>
        <Cell><Data ss:Type="String">added at</Data></Cell>
        <Cell><Data ss:Type="String">department</Data></Cell>
        <Cell><Data ss:Type="String">content</Data></Cell>
        <Cell><Data ss:Type="String">software</Data></Cell>
        <Cell><Data ss:Type="String">system</Data></Cell>
        <Cell><Data ss:Type="String">owner</Data></Cell>
      </Row>
      <% @disks.each do |disk| %>
        <Row>
          <% case disk.capacity
             when 4000001..10000000 %>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.unit_to_hex.upcase %></Data></Cell>
            <% if disk.empty? %>
             <Cell ss:StyleID="free"><Data ss:Type="String"><%= disk.volume %></Data></Cell>
            <% else %>
             <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.volume %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.group.name if disk.group %></Data></Cell>
            <Cell ss:StyleID="s9"><Data ss:Type="Number"><%= disk.custom_capacity('GB') %></Data></Cell>
            <% if disk.utilization.between?(70,90) %>
             <Cell ss:StyleID="utilMed"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% elsif disk.utilization.between?(91,100) %>
             <Cell ss:StyleID="utilHigh"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% else%>
             <Cell ss:StyleID="s9"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.pprc_secondary %></Data></Cell>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.dtap %></Data></Cell>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.added_at %></Data></Cell>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.department.name if disk.department %></Data></Cell>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.content.name if disk.content %></Data></Cell>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.software.name if disk.software %></Data></Cell>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.systems.map{|s| s.name}.join(' ') %></Data></Cell>
            <Cell ss:StyleID="s9"><Data ss:Type="String"><%= disk.owner.name %></Data></Cell>
          <% when 10000001..28000000 %>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.unit_to_hex.upcase %></Data></Cell>
            <% if disk.empty? %>
              <Cell ss:StyleID="free"><Data ss:Type="String"><%= disk.volume %></Data></Cell>
            <% else %>
              <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.volume %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.group.name if disk.group %></Data></Cell>
            <Cell ss:StyleID="s27"><Data ss:Type="Number"><%= disk.custom_capacity('GB') %></Data></Cell>
            <% if disk.utilization.between?(70,90) %>
              <Cell ss:StyleID="utilMed"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% elsif disk.utilization.between?(91,100) %>
              <Cell ss:StyleID="utilHigh"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% else%>
              <Cell ss:StyleID="s27"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.pprc_secondary %></Data></Cell>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.dtap %></Data></Cell>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.added_at %></Data></Cell>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.department.name if disk.department %></Data></Cell>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.content.name if disk.content %></Data></Cell>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.software.name if disk.software %></Data></Cell>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.systems.map{|s| s.name}.join(' ') %></Data></Cell>
            <Cell ss:StyleID="s27"><Data ss:Type="String"><%= disk.owner.name %></Data></Cell>
          <% when 28000001..Float::INFINITY %>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.unit_to_hex.upcase %></Data></Cell>
            <% if disk.empty? %>
              <Cell ss:StyleID="free"><Data ss:Type="String"><%= disk.volume %></Data></Cell>
            <% else %>
              <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.volume %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.group.name if disk.group %></Data></Cell>
            <Cell ss:StyleID="s54"><Data ss:Type="Number"><%= disk.custom_capacity('GB') %></Data></Cell>
            <% if disk.utilization.between?(70,90) %>
              <Cell ss:StyleID="utilMed"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% elsif disk.utilization.between?(91,100) %>
              <Cell ss:StyleID="utilHigh"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% else%>
              <Cell ss:StyleID="s54"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.pprc_secondary %></Data></Cell>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.dtap %></Data></Cell>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.added_at %></Data></Cell>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.department.name if disk.department %></Data></Cell>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.content.name if disk.content %></Data></Cell>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.software.name if disk.software %></Data></Cell>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.systems.map{|s| s.name}.join(' ') %></Data></Cell>
            <Cell ss:StyleID="s54"><Data ss:Type="String"><%= disk.owner.name %></Data></Cell>
          <% else %>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.unit_to_hex.upcase %></Data></Cell>
            <% if disk.empty? %>
              <Cell ss:StyleID="free"><Data ss:Type="String"><%= disk.volume %></Data></Cell>
            <% else %>
              <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.volume %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.group.name if disk.group %></Data></Cell>
            <Cell ss:StyleID="s3"><Data ss:Type="Number"><%= disk.custom_capacity('GB') %></Data></Cell>
            <% if disk.utilization.between?(70,90) %>
              <Cell ss:StyleID="utilMed"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% elsif disk.utilization.between?(91,100) %>
              <Cell ss:StyleID="utilHigh"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% else%>
              <Cell ss:StyleID="s3"><Data ss:Type="Number"><%= disk.utilization %></Data></Cell>
            <% end %>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.pprc_secondary %></Data></Cell>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.dtap %></Data></Cell>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.added_at %></Data></Cell>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.department.name if disk.department %></Data></Cell>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.content.name if disk.content %></Data></Cell>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.software.name if disk.software %></Data></Cell>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.systems.map{|s| s.name}.join(' ') %></Data></Cell>
            <Cell ss:StyleID="s3"><Data ss:Type="String"><%= disk.owner.name %></Data></Cell>
          <% end %>
        </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/disks/index.xlsx.slim
table border="1"
  tr
    th unit
    th volume
    th sms group
    th capacity
    th utilization
    th pprc secondary
    th dev/test/acc/prod
    th added at
    th department
    th content
    th software
    th system
    th owner
  - @disks.each do |disk|
    tr bgcolor=capacity_color(disk)
      td class="excel_text" = disk.unit_to_hex
      td = disk.volume
      td = disk.group.name if disk.group
      td
        = disk.custom_capacity('GB')
      td bgcolor=utilization_color(disk)
        = disk.utilization
      td = disk.pprc_secondary
      td = disk.dtap
      td = disk.added_at
      td = disk.department.name if disk.department
      td = disk.content.name if disk.content
      td = disk.software.name if disk.software
      td
        - disk.systems.each do |system|
          = t("\r#{system.name}")
      td = disk.owner.name

app/views/disks/show.html.slim
h1 align = 'center'  Disk #{@disk.volume}
div class='container-fluid'
  = link_to 'Edit', '#', id: "editButton"
  #edit_form
    = render 'disks/edit_disk', method: :patch
div class='container-fluid'
  = link_to 'Delete', @disk, method: :delete, data: { confirm: 'Are you sure?' }
div class='container-fluid'
  table class="table table-bordered"
    tr
      th unit
      th volume
      th sms group
      th capacity
      th utilization
      th pprc secondary
      th dev/test/acc/prod
      th added at
      th department
      th content
      th software
      th systems
      th owner
    = render @disk
    / = render 'disks/edit_disk
h2 Utilization chart
div class='container-fluid'
  #disk-chart
    = column_chart utilization_chart(@disk)